language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

before_install:
  - composer selfupdate

install:
    - composer install --prefer-source --no-interaction

script:
    - bin/phpunit

notifications:
    email: false
